apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-cert-expiry-exporter
  # labels:
spec:
  endpoints:
    - interval: 30s
      path: /index.php
      scheme: http
      targetPort: 80
  # jobLabel: cert-expiry-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      run: cert-expiry-exporter